---
title: "Median sale prices across Sydney Leichhardt suburbs in 2021"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Median sale prices across Sydney Leichhardt suburbs in 2021}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

We load necessary non-base R libraries.

```{r setup, warnings = FALSE, message = FALSE}
library(allhomes)
library(tidyverse)
library(ggbeeswarm)
```

Download 2021 past sales data for all Leichhardt suburbs. We use the internal dataset `divisions_NSW` to create a `character` vector of all suburbs within the SA3 Leichhardt area.

```{r download-data, cache = TRUE}
# Get all Leichhardt suburbs
suburbs <- divisions_NSW %>%
    filter(sa3_name_2016 == "Leichhardt") %>%
    unite(suburb, division, state, sep = ", ") %>%
    pull(suburb)
suburbs

# Get data for Leichhardt suburbs
years <- 2021L
data <- get_past_sales_data(suburbs, years)
```

We show the distribution and median value of sale prices of properties across different suburbs in the Sydney Leichhardt area in 2021.

```{r plot-sales-data, fig.height = 5, out.width = "100%"}
# Plot
data %>%
    filter(!is.na(price), price > 1e3) %>%
    ggplot(aes(division, price)) +
    geom_quasirandom() +
    stat_summary(fun = median, geom = "crossbar", lwd = 0.5) +
    scale_y_continuous(
        labels = scales::label_dollar(scale = 1e-6, suffix = "M")) +
    labs(x = "Leichhardt suburb", y = "Sales price") +
    theme_minimal()
```
