---
title: "Price as a function of the no. of bedrooms across three North Canberra suburbs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Price as a function of the no. of bedrooms across three North Canberra suburbs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

We load necessary non-base R libraries.

```{r setup, warning = FALSE, message = FALSE}
library(allhomes)
library(tidyverse)
```

Download past sale data for three northern Canberra suburbs from the last 5 years.

```{r download-data, cache = TRUE}
# Get data for three ACT suburbs from the last 5 years 
suburbs <- c("Watson, ACT", "Ainslie, ACT", "Downer, ACT")
years <- 2018L:2022L
data <- get_past_sales_data(suburbs, years)
```

We show the distribution of sale prices as a function of the number of bedrooms.

```{r plot-sales-prices}
# Plot
data %>%
    filter(!is.na(bedrooms), bedrooms > 0, price > 0) %>%
    ggplot(aes(as.factor(bedrooms), price)) +
    geom_boxplot() +
    scale_y_continuous(
        labels = scales::label_dollar(scale = 1e-6, suffix = "M")) +
    facet_wrap(~ division) +
    labs(x = "No. of bedrooms", y = "Sales price") +
    theme_minimal()
```
